Parser combinator for Rib and function_name parser reuse
golemcloud/golem pull request #617
Opened 2024-06-25 13:27 UTC by afsalthaj

2024-06-25 13:31 UTC, afsalthaj commented on golem-rib/src/parser/call.rs
> +            while nesting > 0 {
I think this termination condition is wrong as matching brace may be missing forever and this never ends. I will see to it.

2024-06-26 11:21 UTC, vigoo commented
You will have to add version-override / publishing things into the `Makefile.toml` to make `cargo make publish` work

2024-06-26 11:24 UTC, vigoo requested changes
Looks nice, just please set up the publishing in cargo-make

2024-06-28 10:25 UTC, vigoo approved these changes

2024-06-28 10:25 UTC, merged